#!/bin/bash
export LC_ALL=C
export LANG=C


function count_challenges_of_visitors {
	while read name; do
		win=`visitor_challenges "$1" $name "$2" | grep Winner | wc -l`
		los=`visitor_challenges "$1" $name "$2" | grep Loser | wc -l`
		total=`visitor_challenges "$1" $name "$2" | wc -l`
		echo $name $win $los $total
	done 
}

last_visitors "$1" | count_challenges_of_visitors "$1" "$2" \
		| sort -sk1 | sort -rnsk4 | cut -d" " -f1-3
