#!/bin/bash
function search_file {
	n=1
	while read line; do
		if [[ $line = *"$1"* ]]; then
			echo “${2} : ${n} : $line”
		fi
		let n++;
	done < "$2"
}
for file in ${*:2}; do
	if [[ -f "$file" ]]; then
		search_file "$1" $file
	fi
	if [[ -d "$file" ]]; then
		search "$1" $file/*
	fi
done
