#!/bin/bash

function vstList {
	cat "$1"/visitors.txt
}

function filterVisitor {
	count=0
	while read line; do
	  name=$( echo "$line" |cut -d" " -f3 )
		if [[ $name == "$1" ]]; then
			echo "$line" |cut -d" " -f1,2
		fi
	done
}

vstList "$1" | sort -k2 | filterVisitor "$2" 

