#!/bin/bash

function challenges {
	while read -a line; do
		search_exact "visit id: ${line[1]}" "$1"/challenges/*.chg
	done 
}

function main {
	while read -a file; do
		wol="Loser"		
		while read line; do
			tmp=${line[0]}	
			if [[ $tmp == "overall time:"* ]]; then 
				if (( `echo ${tmp[0]} | cut -d" " -f3` < "$1" )); then
					wol="Winner"
				fi	
			fi
		done < ${file[0]}
		echo ${file[6]} $wol
	done
}

room="$1"
visitor_for_room $room "$2" | challenges $room | main "$3"
